site_name: 'Splunk AWS DevDay Workshop'
site_description: 'This workshop is going to take you through the best-in-class observability solution for ingesting, monitoring, visualizing and analyzing data'
site_author: 'Sales Engineering'
site_url: 'https://signalfx.github.io/observability-workshop/'
repo_url: 'https://github.com/signalfx/observability-workshop/'
edit_uri: ''
copyright: Copyright &copy; 2020 Splunk Inc. All rights reserved.
remote_branch: gh-pages

versions:
  - v1.33
  - v1.32
  - v1.31
  - v1.30
  - v1.29
  - v1.28
  - v1.27
  - v1.26
  - v1.25
  - v1.24
  - v1.23
  - v1.22
  - v1.21
  - v1.20
  - v1.19
  - v1.18
  - v1.17
  - v1.16
  - v1.15
  - v1.14
  - v1.13
  - v1.12
  - v1.11
  - v1.10
  - v1.9
  - v1.8
  - v1.7
  - v1.6
  - v1.5
  - v1.4
  - v1.3
  - v1.2

theme:
  name: material
  palette:
    scheme: preference
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Roboto
    code: Ubuntu Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: material
  features:
    - tabs

markdown_extensions:
  - footnotes   
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - "javascripts/extra.js"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/signalfx/observability-workshop
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splunk/

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: en
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        
nav:
  - 'Home': index.md
  - '<b>Amazon EKS</b>':
      - 'Create EKS Cluster': eks-cluster/readme-b.md
  - '<b>SignalFx</b>':
    - '<b>Get Data In</b><br /><small>20 minutes</small>':
      - 'Workshop Introduction': smartagent/index.md
#      - 'Workshop Preparation': smartagent/prep.md
      - 'Deploy the Smart Agent in EKS': smartagent/k3s.md
    - '<b>Deploy Applications</b>':  
      - 'Deploy NGINX in EKS' : smartagent/nginx.md
      - 'Deploy Mario in EKS' : smartagent/mario.md
      - 'Deploy Imagesample in EKS' : smartagent/imagesample.md
      - 'Deploy CronJob Hungry in EKS' : smartagent/hungry.md
    - '<b>Dashboards</b><br /><small>30 minutes</small>':
      - 'Introduction': dashboards/index.md
      - 'Editing charts': dashboards/editing.md
      - 'Using filters': dashboards/filtering.md
      - 'Using formulas': dashboards/formulas.md
      - 'Using overlays': dashboards/overlay.md
      - 'SignalFlow': dashboards/signalflow.md
      - 'Adding charts': dashboards/adding-charts.md
      - 'Integration to Splunk': dashboards/datalinks.md
    - '<b>Detectors</b><br /><small>15 minutes</small>':
      - 'Creating a Detector': detectors/detectors.md
      - 'Creating a Muting Rule': detectors/muting.md
    - '<b>Monitoring as Code</b><br /><small>10 minutes</small>':
      - 'Initial Setup': monitoring-as-code/index.md
      - 'Plan, Apply and Destroy': monitoring-as-code/plan-and-apply.md
    - '<b>Service Bureau</b><br /><small>20 minutes</small>':
        - 'Billing and Usage' : servicebureau/billing-and-usage.md
        - 'Teams' : servicebureau/teams.md
#    - '<b>Post Workshop Clean Up</b>': module-support/cleanup.md
#    - '<b>Optional Modules</b>':
#      - 'Deploying Sock Shop in K3s': apm/sockshop.md
#      - 'Deploying Hot R.O.D. in EKS': module-support/hotrod-eks.md
#      - 'Deploy Smart Agent on a VM': module-support/vm.md
  - '<b>Splunk Cloud</b>':
    - '<b>Signing up and Getting Started</b><br /><small>30 minutes</small>':
      - 'Signing Up': splunk/index.md
      - 'Creating Index': splunk/splunkindex.md
      - 'Creating HEC Token': splunk/hectoken.md
      - 'Deploying Splunk Connect for Kubernetes': splunk/sck.md
      - 'Setting up Data Links for Contextual Logging': splunk/datalinks.md
  - '<b>Exercises</b>':
      - 'Mission Possible': splunk/solution.md   
  - '<b>Resources</b>':
    - 'Links': resources/index.md
    - 'FAQ': resources/faq.md
