apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hungry-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hungry
        spec:
          containers:
          - name: hungry
            image: busybox
            args:
            - /bin/sh
            - -c
            - "date; echo Hello from the Kubernetes cluster; sleep 70"
            resources:
              requests:
                cpu: "5000m"
                memory: "32234Mi"
          restartPolicy: OnFailure
